
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/banco_desafio?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: joao
    password: minhaSenha
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace


